version: '3.8'

services:
  neos:
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    environment:
      FLOW_CONTEXT: 'Development/Docker'
      COMPOSER_CACHE_DIR: '/composer_cache'
      # DB connection
      DB_NEOS_HOST: 'db'
      DB_NEOS_PORT: 3306
      DB_NEOS_PASSWORD: 'neos'
      DB_NEOS_USER: 'neos'
      DB_NEOS_DATABASE: 'neos'
      # Neos
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'password'
      # cache
      REDIS_HOST: 'redis-cache'
      REDIS_PORT: 6379
    volumes:
      - ./composer.json:/app/composer.json:cached
      # Explicitly set up Composer cache for faster fetching of packages
      - ./tmp/composer_cache:/composer_cache:cached
      # Code
      - ./DistributionPackages:/app/DistributionPackages:cached
      - ./Packages:/app/Packages:cached
      - ./Configuration:/app/Configuration:cached
    ports:
      - '8081:8081'
    depends_on:
      - db
      - redis-cache

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: neos
      MYSQL_DATABASE: neos
      MYSQL_USER: neos
      MYSQL_PASSWORD: neos
    volumes:
      - db:/var/lib/mysql
    ports:
      - '13306:3306'

  redis-cache:
    image: redis:6.2.2
    ports:
      - 16379:6379

volumes:
  db:
